"""Crear tablas iniciales con login

Revision ID: 3ed79bf2d801
Revises: 
Create Date: 2025-06-18 16:41:55.850667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed79bf2d801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('financial_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ingresos', sa.Float(), nullable=False),
    sa.Column('gasto_comida', sa.Float(), nullable=False),
    sa.Column('gasto_transporte', sa.Float(), nullable=False),
    sa.Column('gasto_vivienda', sa.Float(), nullable=False),
    sa.Column('gasto_otros', sa.Float(), nullable=False),
    sa.Column('deudas', sa.Float(), nullable=False),
    sa.Column('ahorros', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_data_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_data_user_id'))

    op.drop_table('financial_data')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    # ### end Alembic commands ###
